### PR TITLE
Bump version. Fix error handling to match new API

### PR DESCRIPTION
**Pull request by xcskier56**

### CODE REVIEW

**Comment by DaneLyons** [comment]
Thanks for the PR!

**Comment by DaneLyons** [comment]
Everything looks good. Tests pass. I don't actually use this gem so I'll have to run a few manual tests to verify.

**Comment by xcskier56** [comment]
One of the key changes that I made to the tests is to make the tests that actually hit the API conditional on having `ENV['KNOWTIFY_API_KEY']` That way when they are not run if there is not api key.

**Comment by xcskier56** [comment]
Also, If you have some sort of documentation on what all of the API endpoints and responses look like that would be super helpful. I'd like to get more sample responses in to be tested.

Thanks for the quick response!

**Pull request merged**
